# Generated by Django 2.2.7 on 2019-11-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arepo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='achievements',
            field=models.ManyToManyField(default=None, to='arepo.Achievement'),
        ),
    ]
