# Generated by Django 2.2.7 on 2019-11-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arepo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dishes',
            field=models.ManyToManyField(related_name='order_dishes', to='arepo.Dish'),
        ),
    ]
