# Generated by Django 2.2.7 on 2019-11-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arepo', '0002_auto_20191116_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='achievements',
            field=models.ManyToManyField(blank=True, to='arepo.Achievement'),
        ),
    ]
