# Generated by Django 2.2.7 on 2019-11-24 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arepo', '0002_order_paid_amount'),
        ('arepo', '0002_auto_20191124_1039'),
    ]

    operations = [
    ]
