# Generated by Django 2.2.7 on 2019-11-24 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arepo', '0003_merge_20191124_1127'),
        ('arepo', '0003_merge_20191124_1257'),
    ]

    operations = [
    ]
