# Generated by Django 2.2.7 on 2019-11-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arepo', '0004_merge_20191124_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='earned',
            field=models.BooleanField(default=False),
        ),
    ]
